# Generated by Django 3.2.7 on 2021-11-09 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idPaciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('pacNmDocumento', models.CharField(max_length=11, unique=True, verbose_name='Número Documento')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('pacNombres', models.CharField(max_length=45, verbose_name='Nombres Paciente')),
                ('pacApellidos', models.CharField(max_length=45, verbose_name='Apellidos Paciente')),
                ('pacFechaNacimiento', models.DateField()),
                ('pacTipoDocumento', models.CharField(max_length=20, verbose_name='Tipo Documento')),
                ('pacDireccion', models.CharField(max_length=60, verbose_name='Dirección')),
                ('pacTelefono', models.CharField(max_length=11, verbose_name='Número Teléfono')),
                ('pacEmail', models.EmailField(max_length=45, verbose_name='Email')),
                ('pacGenero', models.CharField(max_length=9, verbose_name='Género')),
                ('pacEstado', models.BooleanField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False)),
                ('citFecha', models.DateField()),
                ('citHora', models.TimeField()),
                ('citObservacion', models.CharField(max_length=256, verbose_name='Observación de la Cita')),
                ('citEspecialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('citAsignada', models.BooleanField(default=False)),
                ('idPacientefk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cita', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
